timApp/document/course/routes.py
"""
Contains course related routes.
"""

from flask import Blueprint
from sqlalchemy.orm import joinedload

from timApp.auth.sessioninfo import get_current_user_object
from timApp.bookmark.bookmarks import Bookmarks
from timApp.document.docentry import DocEntry, get_documents
from timApp.item.block import Block
from timApp.util.flask.responsehelper import json_response

course_blueprint = Blueprint('course',
                             __name__,
                             url_prefix='/courses')


@course_blueprint.route("/settings")
def get_course_settings():
    """
    Get course settings from the designated settings document.
    :return: Settings from the course settings.
    """
    d = DocEntry.find_by_path("settings/courses")
    if not d:
        return json_response({})
    return json_response(d.document.get_settings().get_dict().values)


@course_blueprint.route("/documents/<string:foldername>")
def get_documents_from_bookmark_folder(foldername):
    """
    Gets documents and their tags based on a bookmark folder name.
    :param foldername:
    :return:
    """
    folder = None
    paths = []
    bookmark_folders = Bookmarks(get_current_user_object())
    for bookmark_folder in bookmark_folders.as_dict():
        if bookmark_folder['name'] == foldername:
            folder = bookmark_folder
    if folder:
        for bookmark in folder['items']:
            paths.append(bookmark['link'].replace("/view/", "", 1))
    else:
        return json_response([])
    docs = get_documents(filter_user=get_current_user_object(),
                         custom_filter=DocEntry.name.in_(paths),
                         query_options=joinedload(DocEntry._block).joinedload(Block.tags))
    return json_response(docs)

timApp/document/routes.py
from typing import Optional

from dataclasses import dataclass
from flask import Response, abort, request, Blueprint
from webargs.flaskparser import use_args

from timApp.auth.accesshelper import get_doc_or_abort, verify_edit_access, can_see_par_source, verify_copy_access
from timApp.auth.sessioninfo import get_current_user_object
from timApp.document.docparagraph import DocParagraph
from timApp.document.document import Document
from timApp.document.documentversion import DocumentVersion
from timApp.modules.py.marshmallow_dataclass import class_schema
from timApp.timdb.exceptions import TimDbException
from timApp.util.flask.requesthelper import get_option
from timApp.util.flask.responsehelper import json_response

doc_bp = Blueprint('document',
                   __name__,
                   url_prefix='')


@doc_bp.route('/download/<int:doc_id>')
def download_document(doc_id):
    d = get_doc_or_abort(doc_id)
    verify_copy_access(d)
    return return_doc_content(d.document)


def return_doc_content(d: Document):
    use_raw = get_option(request, 'format', 'md') == 'json'
    if use_raw:
        return json_response(d.export_raw_data())
    else:
        return Response(d.export_markdown(), mimetype="text/plain")


@doc_bp.route('/download/<int:doc_id>/<int:major>/<int:minor>')
def download_document_version(doc_id, major, minor):
    d = get_doc_or_abort(doc_id)
    verify_edit_access(d)
    doc = DocumentVersion(doc_id, (major, minor))
    if not doc.exists():
        abort(404, "This document version does not exist.")
    return return_doc_content(doc)


@doc_bp.route('/diff/<int:doc_id>/<int:major1>/<int:minor1>/<int:major2>/<int:minor2>')
def diff_document(doc_id, major1, minor1, major2, minor2):
    d = get_doc_or_abort(doc_id)
    verify_edit_access(d)
    doc1 = DocumentVersion(doc_id, (major1, minor1))
    doc2 = DocumentVersion(doc_id, (major2, minor2))
    if not doc1.exists():
        abort(404, f"The document version {(major1, minor1)} does not exist.")
    if not doc2.exists():
        abort(404, f"The document version {(major2, minor2)} does not exist.")
    return Response(DocumentVersion.get_diff(doc1, doc2), mimetype="text/html")


@dataclass
class GetBlockModel:
    doc_id: int
    par_id: str
    area_start: Optional[str] = None
    area_end: Optional[str] = None
    par_hash: Optional[str] = None
    use_exported: bool = True


GetBlockModelSchema = class_schema(GetBlockModel)


@doc_bp.route("/getBlock/<int:doc_id>/<par_id>")
def get_block(doc_id, par_id):
    return get_block_2(GetBlockModel(
        area_end=request.args.get('area_end'),
        area_start=request.args.get('area_start'),
        doc_id=doc_id,
        par_id=par_id,
    ))


@doc_bp.route("/getBlock")
@use_args(GetBlockModelSchema())
def get_block_schema(args: GetBlockModel):
    return get_block_2(args)


def get_block_2(args: GetBlockModel):
    d = get_doc_or_abort(args.doc_id)
    area_start = args.area_start
    area_end = args.area_end
    if area_start and area_end:
        verify_copy_access(d)
        try:
            section = d.document.export_section(area_start, area_end)
        except TimDbException as e:
            return abort(404, 'Area not found. It may have been deleted.')
        return json_response({"text": section})
    else:
        try:
            p = d.document.get_paragraph(args.par_id)
            if not can_see_par_source(get_current_user_object(), p):
                abort(403)
            if args.par_hash:
                par = DocParagraph.get(d.document, args.par_id, args.par_hash or p.get_hash())
            else:
                par = p
        except TimDbException as e:
            return abort(404, 'Paragraph not found. It may have been deleted.')
        if args.use_exported:
            return json_response({"text": par.get_exported_markdown()})
        else:
            return json_response({"text": par.get_markdown()})

timApp/item/routes.py
"""Routes for document view."""
import time
import traceback
from typing import Tuple, Optional, List, Union

import attr
from dataclasses import dataclass
from flask import Blueprint, render_template, make_response, abort
from flask import current_app
from flask import flash
from flask import g
from flask import redirect
from flask import request
from flask import session
from marshmallow import ValidationError

from marshmallow_dataclass import class_schema
from timApp.answer.answers import add_missing_users_from_group, get_points_by_rule
from timApp.auth.accesshelper import verify_view_access, verify_teacher_access, verify_seeanswers_access, \
    get_rights, has_edit_access, get_doc_or_abort, verify_manage_access
from timApp.auth.auth_models import BlockAccess
from timApp.auth.sessioninfo import get_current_user_object, logged_in, current_user_in_lecture, \
    save_last_page
from timApp.document.create_item import create_or_copy_item, create_citation_doc
from timApp.document.docentry import DocEntry, get_documents
from timApp.document.docinfo import DocInfo
from timApp.document.docparagraph import DocParagraph
from timApp.document.docsettings import DocSettings
from timApp.document.document import get_index_from_html_list, dereference_pars, Document
from timApp.document.post_process import post_process_pars, \
    hide_names_in_teacher
from timApp.document.preloadoption import PreloadOption
from timApp.folder.folder import Folder
from timApp.folder.folder_view import try_return_folder
from timApp.item.block import BlockType
from timApp.item.blockrelevance import BlockRelevance
from timApp.item.item import Item
from timApp.item.partitioning import get_piece_size_from_cookie, decide_view_range, get_doc_version_hash, load_index, \
    INCLUDE_IN_PARTS_CLASS_NAME, save_index, partition_texts, get_index_with_header_id, get_document_areas, \
    RequestedViewRange, IndexedViewRange
from timApp.item.tag import GROUP_TAG_PREFIX
from timApp.item.validation import has_special_chars
from timApp.markdown.htmlSanitize import sanitize_html
from timApp.markdown.markdownconverter import create_environment
from timApp.plugin.plugin import find_task_ids
from timApp.plugin.pluginControl import get_all_reqs
from timApp.tim_app import app
from timApp.timdb.exceptions import TimDbException, PreambleException
from timApp.timdb.sqa import db
from timApp.user.groups import verify_group_view_access
from timApp.user.user import User
from timApp.user.usergroup import UserGroup, get_usergroup_eager_query, UserGroupWithSisuInfo
from timApp.user.users import get_rights_holders_all
from timApp.util.flask.requesthelper import verify_json_params, use_model
from timApp.util.flask.responsehelper import json_response, ok_response, get_grid_modules
from timApp.util.logger import log_error
from timApp.util.timtiming import taketime
from timApp.util.utils import get_error_message, cache_folder_path
from timApp.util.utils import remove_path_special_chars, seq_to_str

DEFAULT_RELEVANCE = 10

view_page = Blueprint('view_page',
                      __name__,
                      url_prefix='')

DocumentSlice = Tuple[List[DocParagraph], IndexedViewRange]
ViewRange = Union[RequestedViewRange, IndexedViewRange]

def get_partial_document(doc: Document, view_range: ViewRange) -> DocumentSlice:
    all_pars = doc.get_paragraphs()

    # Handle common unrestricted case first.
    if view_range.is_full:
        return all_pars, IndexedViewRange(b=0, e=len(all_pars), par_count=len(all_pars))

    si = view_range.start_index
    ei = view_range.end_index
    if isinstance(view_range, RequestedViewRange):
        spid = view_range.start_par_id
        epid = view_range.end_par_id
    else:
        spid = None
        epid = None
    actual_start_index = None
    actual_end_index = None
    if si is not None and ei is not None:
        actual_start_index = si
        actual_end_index = ei
    elif si is not None:
        actual_start_index = si
    elif ei is not None:
        actual_end_index = ei
    else:
        for i, par in enumerate(all_pars):
            if par.get_id() == epid:
                actual_end_index = i
            if par.get_id() == spid:
                actual_start_index = i
            if actual_start_index is not None and actual_end_index is not None:
                break
    if actual_start_index is None:
        actual_start_index = 0
    if actual_end_index is None:
        actual_end_index = len(all_pars) if view_range.size is None else actual_start_index + view_range.size
    pars = all_pars[actual_start_index:actual_end_index]
    return pars, IndexedViewRange(b=actual_start_index, e=actual_end_index, par_count=len(all_pars))


def get_document(doc_info: DocInfo, view_range: ViewRange) -> DocumentSlice:
    doc = doc_info.document
    doc.preload_option = PreloadOption.all
    return get_partial_document(doc, view_range)


@dataclass
class ViewModel:
    b: Union[int, str, None] = None
    e: Union[int, str, None] = None
    size: Union[int, None] = None
    edit: Optional[str] = None
    group: Optional[str] = None
    hide_names: Optional[bool] = None
    lazy: Optional[bool] = None
    login: bool = False
    noanswers: bool = False
    nocache: bool = False
    pars_only: bool = False
    preamble: bool = False

    def __post_init__(self):
        if self.b and self.e:
            if type(self.b) != type(self.e):
                raise ValidationError('b and e must be of same type (int or string).')
        if self.e is not None and self.size is not None:
            raise ValidationError('Cannot provide e and size parameters at the same time.')

ViewModelSchema = class_schema(ViewModel)()


@view_page.route("/show_slide/<path:doc_name>")
def show_slide(doc_name):
    html = view(doc_name, 'show_slide.html')
    return html


@view_page.route("/view/<path:doc_name>")
def view_document(doc_name):
    taketime("route view begin")
    ret = view(doc_name, 'view_html.html')
    taketime("route view end")
    return ret


@view_page.route("/teacher/<path:doc_name>")
def teacher_view(doc_name):
    return view(doc_name, 'view_html.html', route="teacher")


@view_page.route("/velp/<path:doc_name>")
def velp_view(doc_name):
    return view(doc_name, 'view_html.html', route="velp")


@view_page.route("/answers/<path:doc_name>")
def see_answers_view(doc_name):
    return view(doc_name, 'view_html.html', route="answers")


@view_page.route("/lecture/<path:doc_name>")
def lecture_view(doc_name):
    return view(doc_name, 'view_html.html', route="lecture")


@view_page.route("/slide/<path:doc_name>")
def slide_document(doc_name):
    html = view(doc_name, 'view_html.html', route="slide")
    return html


@view_page.route("/par_info/<int:doc_id>/<par_id>")
def par_info(doc_id, par_id):
    doc = get_doc_or_abort(doc_id)
    verify_view_access(doc)
    for o in doc.owners:
        o.load_personal_user()
    par_name = doc.document.get_closest_paragraph_title(par_id)
    return json_response({
        'item': doc,
        'par_name': par_name,
    })


@dataclass
class GetItemsModel:
    folder: Optional[str] = None
    folder_id: Optional[int] = None
    recursive: bool = False
    include_rights: bool = False


@attr.s(auto_attribs=True)
class ItemWithRights:
    i: Item
    rights: List[BlockAccess]

    def to_json(self):
        return {
            **self.i.to_json(),
            'grouprights': self.rights,
        }


@view_page.route("/getItems")
@use_model(GetItemsModel)
def items_route(args: GetItemsModel):
    if args.folder is not None:
        f = Folder.find_by_path(args.folder)
    elif args.folder_id is not None:
        f = Folder.get_by_id(args.folder_id)
    else:
        return abort(400)
    if not f:
        return abort(404, 'Folder not found.')
    if not f.is_root():
        verify_view_access(f)

    items = get_items(f.path, recurse=args.recursive)
    if args.include_rights:
        u = get_current_user_object()
        rights = get_rights_holders_all([i.id for i in items if u.has_manage_access(i)], order_by=BlockAccess.type)
        items = [ItemWithRights(i, rights[i.id]) for i in items]
    return json_response(items)


@view_page.route("/view")
def index_page():
    save_last_page()
    in_lecture = current_user_in_lecture()
    return render_template('index.html',
                           items=get_items(''),
                           in_lecture=in_lecture,
                           item=Folder.get_root())


debug_time = time.time()


def show_time(s):
    global debug_time
    now = time.time()
    print(s, now - debug_time)
    debug_time = now


def get_module_ids(js_paths: List[str]):
    for jsfile in js_paths:
        yield jsfile.lstrip('/').rstrip('.js')


def view(item_path, template_name, route="view"):
    taketime("view begin", zero=True)
    m: ViewModel = ViewModelSchema.load(request.args, unknown='EXCLUDE')
    usergroup = m.group
    g.viewmode = route in ["view", "velp", "lecture", "slide"]
    g.route = route

    if has_special_chars(item_path):
        return redirect(remove_path_special_chars(request.path) + '?' + request.query_string.decode('utf8'))

    save_last_page()

    doc_info = DocEntry.find_by_path(item_path, fallback_to_id=True)

    if doc_info is None:
        return try_return_folder(item_path)

    doc_info.request = request

    edit_mode = m.edit if has_edit_access(doc_info) else None
    create_environment("%%")  # TODO get macroinf

    if m.hide_names is not None:
        session['hide_names'] = m.hide_names

    should_hide_names = False

    if route == 'teacher':
        if not verify_teacher_access(doc_info, require=False, check_duration=True):
            if verify_view_access(doc_info):
                flash("Did someone give you a wrong link? Showing normal view instead of teacher view.")
                return redirect(f'/view/{item_path}')

    if route == 'answers':

timApp/templates/create_new.html
{% extends "base.html" %}
{% block title %}This page does not yet exist.{% endblock %}
{% block content %}
    <p class="errormsg">{{ message or self.title() }}</p>
    {% if session.user_id %}
        {% if show_create_new %}
            <bootstrap-panel title="Create a new document here">
                <create-item
                        item-type="document"
                        full-path="{{ new_item }}"
                        force="true"
                        {% if forced_template %}
                        template="{{ forced_template }}">
                        {% endif %}
                </create-item>
            </bootstrap-panel>
{#
            <bootstrap-panel title="Create a new folder here">
                <create-item item-type="folder" full-path="{{ new_item }}"></create-item>
            </bootstrap-panel>
#}
        {% else %}
            You cannot create documents or folders here.
        {% endif %}
    {% else %}
        To create a new document or a folder, log in.
    {% endif %}
    {% if found_item %}
        <a href="/view/{{ found_item.path }}">To the first existing item ({{ found_item.title }}) in your search.</a>
    {% else %}
        <a href="{{ url_for('view_page.index_page') }}">To the index.</a>
    {% endif %}
{% endblock %}

timApp/templates/document.html
{% extends 'item.html' %}
{% block head %}
    {{ super() }}
    <script>
        {% if edit_mode %}
        var editMode = {{ edit_mode|tojson }};
        {% else %}
        var editMode = null;
        {% endif %}
    </script>
{% endblock %}

timApp/templates/dumbo_html_error.html
{% extends "error.html" %}
{% block content %}
<p>
    The markdown server failed to render markdown to HTML. This usually means that the mathematical formulas
    in this document are still being processed. This page will refresh periodically. Please wait.
</p>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        window.location.reload();
    });
</script>
{% endblock %}

timApp/templates/duration_unlock.html
{% extends 'item.html' %}
{% block content %}
    <div class="alert alert-warning">
        <i class="glyphicon glyphicon-warning-sign"></i>
        {% if msg %}
            {{ msg }}
        {% elif access.unlockable %}
            You are about to access a time-limited {{ item_type }}.
            After you click Unlock, your access to this {{ item_type }} will be removed in {{ access.duration | timtimedelta }}.
        {% elif access.require_confirm %}
            You can unlock this item only after your permission is confirmed.
        {% elif access.duration_expired %}
            You cannot unlock this item anymore (deadline expired {{ access.duration_to | timreldatetime }}).
        {% elif access.duration_future %}
            You can unlock this item in {{ access.duration_from | timreldatetime }}.
        {% elif access.expired %}
            Your access to this item has expired {{ access.accessible_to | timreldatetime }}.
        {% elif access.future %}
            You can access this item in {{ access.accessible_from | timreldatetime }}.
        {% else %}
            You don't have access to this item.
        {% endif %}
    </div>
    {% if next_doc %}
        <div class="text-center">
            <a href="/view/{{ next_doc.path }}?unlock=true" class="timButton">Go to the next document</a>
        </div>
    {% endif %}
    {% if access.unlockable %}
        <div class="text-center">
            <a href="/view/{{ item.path }}?unlock=true" class="timButton">Unlock</a>
        </div>
    {% endif %}
{% endblock %}

timApp/templates/error.html
{% extends "base.html" %}
{% block title %}{{ code }} {{ status }}{% endblock %}
{% block content %}
    <p class="errormsg">{{ message }}</p>
{% endblock %}

timApp/templates/folder.html
{% extends 'item.html' %}

timApp/templates/index.html
{% extends "folder.html" %}
{% block title %}{{'{} {}'.format(item.title, '({})'.format(item.location) if item.location else '')}}{% endblock %}
{% block head %}
    {{ super() }}

    <script>
        var items = {{ items | tojson }};
    </script>
{% endblock %}

{% set col_m_lg = 10 %}

{% block content %}
    <tim-index></tim-index>
{% endblock %}

timApp/templates/item.html
{% extends 'base.html' %}
{% block head %}
    {{ super() }}
    <script>
        var curr_item = {{item|tojson}};
        var breadcrumbs = {{item.parents_to_root()|tojson}};
        var linked_groups = {{linked_groups|tojson}};
    </script>
{% endblock %}

timApp/templates/lectureInfo.html
{% extends "document.html" %}
{% block title %}Lecture info{% endblock %}
{% block head %}
    {{ super() }}

    <script>
        var lecture = {{lecture|tojson}};
        var inLecture = {{in_lecture|tojson}};
    </script>

{% endblock %}
{% block content %}
<tim-lecture-info></tim-lecture-info>
{% endblock %}

timApp/templates/loginpage.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
            <p class="text-center">
                {% if not hide_require_text %}
                    Login is required for this document.
                {% endif %}
                Please use the above button to log in.
            </p>
        </div>
    </div>
{% endblock %}

timApp/templates/manage.html
{% extends 'item.html' %}
{% block title %}{{ item.title }} - Manage{% endblock %}
{% block head %}
    {{ super() }}
    <script>
        var accessTypes = {{access_types|tojson}};
        var orgs = {{orgs|tojson}};
    </script>
{% endblock %}
{% block content %}
    <tim-manage></tim-manage>
{% endblock %}

timApp/templates/settings.html
{% extends "base.html" %}
{% block title %}Settings{% endblock %}
{% block customcss %}
    {# The logic for custom CSS is dynamic on settings page, so we disable it here. #}
{% endblock %}
{% block head %}
    {{ super() }}
    <script>
        var css_files = {{ css_files|tojson }};
        var notifications = {{ notifications|tojson }};
        var notificationLimit = {{ notification_limit|tojson }};
    </script>
{% endblock %}
{% block content %}
    <tim-settings></tim-settings>
{% endblock %}

timApp/templates/show_slide.html
{% extends 'view_html.html' %}
{# The custom style should be the last style element, so don't render it in view_html.html #}
{% block viewhtml_customcss %}{% endblock %}
{% block head %}
    {{ super() }}
    <meta name="apple-mobile-web-app-capable" content="yes"/>
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"/>
    {% include 'partials/doc_customcss.html' %}
    <script>
        var background_url = {{ (slide_background_url or None)|tojson }};
        var background_color = {{ (slide_background_color or None)|tojson }};
    </script>
{% endblock %}

{% block body %}
    <tim-view>
    <div class="reveal" style="visibility: hidden">
        <div class="slides paragraphs">
            <section>
                {# Because of Jinja2 scoping rules, we need to use a single-element array #}
                {% set prev_is_empty = [True] %}
                {% set sectionchange = '</section><section>'|safe %}
                {% for t in text %}
                    {% if 'settings' in t.attrs %}
                        {# do nothing #}
                    {% elif t.md.startswith('---') and t.md.endswith('---') %}
                        {% if not prev_is_empty[0] %}
                            {{ sectionchange }}
                            {% set _ = prev_is_empty.append(prev_is_empty.pop() or True) %}
                        {% endif %}
                    {% else %}
                        {% if (t.html.startswith("<h1") or
                               t.html.startswith("<h2") or
                               t.html.startswith("<h3")) and not prev_is_empty[0] %}
                            {{ sectionchange }}
                        {% endif %}
                        <div class="{{ t.cls }}"
                             id="{{ t.id }}"
                             t="{{ t.t }}"
                             attrs="{{ t.attrs_str }}">
                            {{ t.html|safe }}
                        </div>
                        {% set _ = prev_is_empty.append(prev_is_empty.pop() and False) %}
                    {% endif %}
                {% endfor %}
            </section>
        </div>
    </div>
    </tim-view>
{% endblock %}